swagger: '2.0'
info:
  x-ibm-name: financing
  title: financing
  version: 1.0.0
schemes:
  - https
host: $(catalog.host)
basePath: /financing
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
security:
  - clientIdHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
      - invoke:
          target-url: $(target-url)$(request.path)
  targets:
    financingService:
      swagger: '2.0'
      info:
        title: financingService
        description: ''
        x-ibm-name: financingservice
        version: 1.0.0
      schemes:
        - https
      basePath: /financingService
      produces:
        - application/xml
      consumes:
        - text/xml
      securityDefinitions:
        clientID:
          type: apiKey
          name: X-IBM-Client-Id
          in: header
          description: ''
      security:
        - clientID: []
      x-ibm-configuration:
        type: wsdl
        wsdl-definition:
          wsdl: 'https://thinkibm-services.mybluemix.net/financing/calculate?wsdl'
          service: financingService
          port: financingPort
          soap-version: '1.1'
        assembly:
          execute:
            - proxy:
                title: proxy
                target-url: 'https://thinkibm-services.mybluemix.net/financing/calculate'
        gateway: datapower-gateway
        enforced: true
        testable: true
        phase: realized
        cors:
          enabled: true
      paths:
        /financing:
          post:
            summary: Operation financing
            description: ''
            operationId: financing
            x-ibm-soap:
              soap-action: 'http://thinkibm-services.mybluemix.net/financing'
              soap-operation: '{http://thinkibm-services.mybluemix.net}financingRequest'
            parameters:
              - in: body
                name: body
                required: true
                schema:
                  $ref: >-
                    #/x-ibm-configuration/targets/financingService/definitions/financingInput
            responses:
              default:
                description: ''
                schema:
                  $ref: >-
                    #/x-ibm-configuration/targets/financingService/definitions/financingOutput
      definitions:
        Security:
          xml:
            namespace: >-
              http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd
            prefix: wsse
          type: object
          properties:
            UsernameToken:
              type: object
              properties:
                Username:
                  type: string
                Password:
                  type: string
        financingInput:
          type: object
          properties:
            Envelope:
              xml:
                prefix: soap-env
                namespace: 'http://schemas.xmlsoap.org/soap/envelope/'
              type: object
              properties:
                Header:
                  $ref: >-
                    #/x-ibm-configuration/targets/financingService/definitions/financingHeader
                Body:
                  type: object
                  properties:
                    financingRequest:
                      $ref: >-
                        #/x-ibm-configuration/targets/financingService/definitions/financingRequest_ser
          example: >-

            <soap-env:Envelope
            xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
             <soap-env:Header>
              <wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
               <UsernameToken>
                <Username>string</Username>
                <Password>string</Password>
               </UsernameToken>
              </wsse:Security>
             </soap-env:Header>
             <soap-env:Body>
              <ser:financingRequest xmlns:ser="http://thinkibm-services.mybluemix.net">
               <ser:amount><!-- mandatory -->string</ser:amount>
               <ser:duration><!-- mandatory -->3</ser:duration>
               <ser:rate><!-- mandatory -->string</ser:rate>
              </ser:financingRequest>
             </soap-env:Body>
            </soap-env:Envelope>
        financingHeader:
          type: object
          properties:
            Security:
              $ref: >-
                #/x-ibm-configuration/targets/financingService/definitions/Security
        financingOutput:
          type: object
          properties:
            Envelope:
              xml:
                prefix: soap-env
                namespace: 'http://schemas.xmlsoap.org/soap/envelope/'
              type: object
              properties:
                Body:
                  type: object
                  properties:
                    financingResult:
                      $ref: >-
                        #/x-ibm-configuration/targets/financingService/definitions/financingResult_ser
          example: >-

            <soap-env:Envelope
            xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
             <soap-env:Body>
              <ser:financingResult xmlns:ser="http://thinkibm-services.mybluemix.net">
               <ser:paymentAmount><!-- mandatory -->string</ser:paymentAmount>
              </ser:financingResult>
             </soap-env:Body>
            </soap-env:Envelope>
        financingRequest_ser:
          xml:
            namespace: 'http://thinkibm-services.mybluemix.net'
            prefix: ser
          type: object
          properties:
            amount:
              type: string
            duration:
              type: number
            rate:
              type: string
          required:
            - amount
            - duration
            - rate
          example: >-

            <ser:financingRequest
            xmlns:ser="http://thinkibm-services.mybluemix.net">
             <ser:amount><!-- mandatory -->string</ser:amount>
             <ser:duration><!-- mandatory -->3</ser:duration>
             <ser:rate><!-- mandatory -->string</ser:rate>
            </ser:financingRequest>
        financingResult_ser:
          xml:
            namespace: 'http://thinkibm-services.mybluemix.net'
            prefix: ser
          type: object
          properties:
            paymentAmount:
              type: string
          required:
            - paymentAmount
          example: >-

            <ser:financingResult
            xmlns:ser="http://thinkibm-services.mybluemix.net">
             <ser:paymentAmount><!-- mandatory -->string</ser:paymentAmount>
            </ser:financingResult>
paths:
  /calculate:
    get:
      responses:
        '200':
          description: 200 OK
          schema:
            $ref: '#/definitions/paymentAmount'
      parameters:
        - name: amount
          type: number
          required: true
          in: query
          description: amount to finance
          format: float
        - name: duration
          type: integer
          required: true
          in: query
          description: length of term in months
          format: int64
        - name: rate
          type: number
          required: true
          in: query
          description: interest rate
          format: float
definitions:
  paymentAmount:
    description: ''
    type: object
    properties:
      paymentAmount:
        type: number
        description: Monthly payment amount
        format: float
        example: 199.99
tags: []
